### ISSUE TITLE
How much memory does this use?

### ISSUE THREAD

**Issue by dflock** [pR0Ps/zipstream-ng#16]
I'm wondering about memory use. The only mention is in the README, which says "without needing temporary files or excessive memory.". I'm assuming that this is all streaming and it's only holding in-flight chunks in memory - but I haven't been able to try it out and verify this yet.

So, what is _actually_ being held in memory? Is it just in-flight chunks, or the whole current file, or what?

Thanks!

**Comment by pR0Ps** [comment]
You're correct in that it's all streaming and mostly only holding in-flight chunks in memory. For example, if you want to zip up 100GB stored across 100 files, you're not going to use anywhere close to 100GB of memory. You'd essentially be storing 100 bits of metadata (path, size, name, etc) and only pulling the bits of the files that are actively being compressed/streamed into memory while the zip is being generated.

For an example, I just ran a quick test against ~8TB of data contained in ~10,000 files and the peak memory usage of the process was ~30MB.

**Comment by dflock** [comment]
Maybe add a version of this to the README?
