### ISSUE TITLE
Usage with FastAPI?

### ISSUE THREAD

**Issue by Wamy-Dev** [pR0Ps/zipstream-ng#18]
Hey there! I tried doing the same thing that you did for Flask using FastAPI, and I but I keep getting the error:

`ZipStream object has no attribute 'encode'`

When trying to serve the stream like this:

```py
zs = ZipStream.from_path(path)
response = Response(
    content = zs,
    headers = {
        "Content-Disposition": f'attachment; filename="file.zip"',
        "Content-Length": str(len(zs)),
        "Last-Modified": zs.last_modified.strftime('%Y-%m-%d %H:%M:%S'),
    }
)
return response
```

When I try and access the bytes directly using:

```py
zs = ZipStream.from_path(path)
response = Response(
    content = zs.__bytes__(),
    headers = {
        "Content-Disposition": f'attachment; filename="file.zip"',
        "Content-Length": str(len(zs)),
        "Last-Modified": zs.last_modified.strftime('%Y-%m-%d %H:%M:%S'),
    }
)
return response
```

it works but the bytes are loaded into memory before serving, which is obviously not okay.

Is there any way to make this work with FastAPI.

**Comment by Wamy-Dev** [comment]
I ended up finding a solution for it, and it was to just stream it.

```py
zs = ZipStream.from_path(path)
stream = gen_zipfile(path)
response = StreamingResponse(
    content = stream,
    headers = {
        "Content-Disposition": f'attachment; filename="file.zip"',
        "Content-Length": str(len(zs)),
        "Last-Modified": zs.last_modified.strftime('%Y-%m-%d %H:%M:%S'),
    }
)
return response
```
```py
def gen_zipfile(path):
    zs = ZipStream.from_path(path)
    yield from zs.finalize()
```

It's a little annoying to have to call zs multiple times but it doesn't cost any extra memory, so with scale it will be fine. 

**I do have another question. Is it possible to generate only part of the zip file? I want to support the range header for multi-connection downloads.**

**Comment by Wamy-Dev** [comment]
I never new iter() existed. Do you have any documentation anywhere?

**Comment by pR0Ps** [comment]
It's a builtin that returns an iterator over an object: https://docs.python.org/3/library/functions.html#iter
