### ISSUE TITLE
Zip from_path bez katalogu

### ISSUE THREAD

**Issue by Elger9** [pR0Ps/zipstream-ng#25]
First of all, thank you for zipstream-ng. I have checked several libs and this is the best tool of its kind. However, I have a problem. When I use 
```
ZipStream.from_path('/storage/data/')
```
This gives me a `zip` file which has a `data` directory and inside it files and directories that are in the `/storage/data/` directory. Is it possible to skip the `data` directory? So that when the ZIP file is opened, the contents of the /storage/data/ directory are directly visible?

Regards

**Comment by pR0Ps** [comment]
This should probably be better documented, but you can use:
```python
ZipStream.from_path("/storage/data/", arcname=".")
```

**Comment by pR0Ps** [comment]
@Elger9 I just made a change to the library to better support this and added a note to the `add_path` docstring. With `zipstream-ng>=1.8.0` use this instead:
 
```python
ZipStream.from_path("/storage/data/", arcname="/")
```

**Comment by Elger9** [comment]
Thanks for quickly adding this feature, it's easy now!
