### ISSUE TITLE
Returning a zip with an empty folder as Flask response never ends

### ISSUE THREAD

**Issue by evil-shrike** [pR0Ps/zipstream-ng#8]
Returning a zip with an empty folder as Flask response hangs indefinitely.

here's a demo:
```
import zipstream
from flask import Response


@app.route("/api/download", methods=["GET"])
def download():
  zs = zipstream.ZipStream(compress_type=zipstream.ZIP_STORED, sized=True)
  zs.add_path('folder_with_data')
  zs.add_path('empty_folder')
  return Response(
      zs,
      mimetype="application/zip",
      headers={
          "Content-Disposition": f"attachment; filename={zip_filename}",
          "Content-Length": len(zs),
          "Last-Modified": zs.last_modified,
      })
```
without the empty dir, everything works as expected, client get data (as an attachment). With the empty dir the server responds with correct headers but no actual data sent.

The issue happens only when we stream to response, if creating a zip locally, then it works.

**Comment by pR0Ps** [comment]
Thanks for the detailed report! I've fixed the issue released it in v1.3.3
